# -*- coding: utf-8 -*-
"""
team_aliases.py — football-data.org 队名 → football-data.co.uk 队名 显式映射表

用途：update_scores.py 快速通道把 football-data.org 的全称队名（如 "Manchester United FC"）
翻译成网站沿用的 football-data.co.uk 短名（如 "Man United"），保证同一场比赛在
football_latest.json 里只有一条记录（去重键 date|team1|team2 一致）。

结构：{ 本站联赛码: { football-data.org 队名: football-data.co.uk 队名 } }

维护：出现「队名未映射，跳过」警告时，把新队名按本表格式补进来即可。
覆盖：9 个赛事 2025-26 赛季现役球队（2026-07 对照两个数据源核实）。
"""

TEAM_ALIASES = {
    # 英超（PL → E0）
    "E0": {
        "AFC Bournemouth": "Bournemouth",
        "Arsenal FC": "Arsenal",
        "Aston Villa FC": "Aston Villa",
        "Brentford FC": "Brentford",
        "Brighton & Hove Albion FC": "Brighton",
        "Burnley FC": "Burnley",
        "Chelsea FC": "Chelsea",
        "Crystal Palace FC": "Crystal Palace",
        "Everton FC": "Everton",
        "Fulham FC": "Fulham",
        "Leeds United FC": "Leeds",
        "Liverpool FC": "Liverpool",
        "Manchester City FC": "Man City",
        "Manchester United FC": "Man United",
        "Newcastle United FC": "Newcastle",
        "Nottingham Forest FC": "Nott'm Forest",
        "Sunderland AFC": "Sunderland",
        "Tottenham Hotspur FC": "Tottenham",
        "West Ham United FC": "West Ham",
        "Wolverhampton Wanderers FC": "Wolves",
    },
    # 英冠（ELC → E1；注意 football-data.co.uk 的 EC 是英议联，英冠是 E1）
    "E1": {
        "Birmingham City FC": "Birmingham",
        "Blackburn Rovers FC": "Blackburn",
        "Bristol City FC": "Bristol City",
        "Charlton Athletic FC": "Charlton",
        "Coventry City FC": "Coventry",
        "Derby County FC": "Derby",
        "Hull City AFC": "Hull",
        "Ipswich Town FC": "Ipswich",
        "Leicester City FC": "Leicester",
        "Middlesbrough FC": "Middlesbrough",
        "Millwall FC": "Millwall",
        "Norwich City FC": "Norwich",
        "Oxford United FC": "Oxford",
        "Portsmouth FC": "Portsmouth",
        "Preston North End FC": "Preston",
        "Queens Park Rangers FC": "QPR",
        "Sheffield United FC": "Sheffield United",
        "Sheffield Wednesday FC": "Sheffield Weds",
        "Southampton FC": "Southampton",
        "Stoke City FC": "Stoke",
        "Swansea City AFC": "Swansea",
        "Watford FC": "Watford",
        "West Bromwich Albion FC": "West Brom",
        "Wrexham AFC": "Wrexham",
    },
    # 德甲（BL1 → D1）
    "D1": {
        "1. FC Heidenheim 1846": "Heidenheim",
        "1. FC Köln": "FC Koln",
        "1. FC Union Berlin": "Union Berlin",
        "1. FSV Mainz 05": "Mainz",
        "Bayer 04 Leverkusen": "Leverkusen",
        "Borussia Dortmund": "Dortmund",
        "Borussia Mönchengladbach": "M'gladbach",
        "Eintracht Frankfurt": "Ein Frankfurt",
        "FC Augsburg": "Augsburg",
        "FC Bayern München": "Bayern Munich",
        "FC St. Pauli 1910": "St Pauli",
        "Hamburger SV": "Hamburg",
        "RB Leipzig": "RB Leipzig",
        "SC Freiburg": "Freiburg",
        "SV Werder Bremen": "Werder Bremen",
        "TSG 1899 Hoffenheim": "Hoffenheim",
        "VfB Stuttgart": "Stuttgart",
        "VfL Wolfsburg": "Wolfsburg",
    },
    # 西甲（PD → SP1）
    "SP1": {
        "Athletic Club": "Ath Bilbao",
        "CA Osasuna": "Osasuna",
        "Club Atlético de Madrid": "Ath Madrid",
        "Deportivo Alavés": "Alaves",
        "Elche CF": "Elche",
        "FC Barcelona": "Barcelona",
        "Getafe CF": "Getafe",
        "Girona FC": "Girona",
        "Levante UD": "Levante",
        "RC Celta de Vigo": "Celta",
        "RCD Espanyol de Barcelona": "Espanol",
        "RCD Mallorca": "Mallorca",
        "Rayo Vallecano de Madrid": "Vallecano",
        "Real Betis Balompié": "Betis",
        "Real Madrid CF": "Real Madrid",
        "Real Oviedo": "Oviedo",
        "Real Sociedad de Fútbol": "Sociedad",
        "Sevilla FC": "Sevilla",
        "Valencia CF": "Valencia",
        "Villarreal CF": "Villarreal",
    },
    # 意甲（SA → I1）
    "I1": {
        "AC Milan": "Milan",
        "AC Pisa 1909": "Pisa",
        "ACF Fiorentina": "Fiorentina",
        "AS Roma": "Roma",
        "Atalanta BC": "Atalanta",
        "Bologna FC 1909": "Bologna",
        "Cagliari Calcio": "Cagliari",
        "Como 1907": "Como",
        "FC Internazionale Milano": "Inter",
        "Genoa CFC": "Genoa",
        "Hellas Verona FC": "Verona",
        "Juventus FC": "Juventus",
        "Parma Calcio 1913": "Parma",
        "SS Lazio": "Lazio",
        "SSC Napoli": "Napoli",
        "Torino FC": "Torino",
        "US Cremonese": "Cremonese",
        "US Lecce": "Lecce",
        "US Sassuolo Calcio": "Sassuolo",
        "Udinese Calcio": "Udinese",
    },
    # 法甲（FL1 → F1）
    "F1": {
        "AJ Auxerre": "Auxerre",
        "AS Monaco FC": "Monaco",
        "Angers SCO": "Angers",
        "FC Lorient": "Lorient",
        "FC Metz": "Metz",
        "FC Nantes": "Nantes",
        "Le Havre AC": "Le Havre",
        "Lille OSC": "Lille",
        "OGC Nice": "Nice",
        "Olympique Lyonnais": "Lyon",
        "Olympique de Marseille": "Marseille",
        "Paris FC": "Paris FC",
        "Paris Saint-Germain FC": "Paris SG",
        "RC Strasbourg Alsace": "Strasbourg",
        "Racing Club de Lens": "Lens",
        "Stade Brestois 29": "Brest",
        "Stade Rennais FC 1901": "Rennes",
        "Toulouse FC": "Toulouse",
    },
    # 荷甲（DED → N1）
    "N1": {
        "AFC Ajax": "Ajax",
        "AZ": "AZ Alkmaar",
        "ADO Den Haag": "Den Haag",
        "SC Cambuur-Leeuwarden": "Cambuur",
        "Willem II Tilburg": "Willem II",
        "FC Groningen": "Groningen",
        "FC Twente '65": "Twente",
        "FC Utrecht": "Utrecht",
        "FC Volendam": "Volendam",
        "Feyenoord Rotterdam": "Feyenoord",
        "Fortuna Sittard": "For Sittard",
        "Go Ahead Eagles": "Go Ahead Eagles",
        "Heracles Almelo": "Heracles",
        "NAC Breda": "NAC Breda",
        "NEC": "Nijmegen",
        "PEC Zwolle": "Zwolle",
        "PSV": "PSV Eindhoven",
        "SBV Excelsior": "Excelsior",
        "SC Heerenveen": "Heerenveen",
        "Sparta Rotterdam": "Sparta Rotterdam",
        "Telstar 1963": "Telstar",
    },
    # 葡超（PPL → P1）
    "P1": {
        "AVS": "AVS",
        "Académico de Viseu FC": "Academico Viseu",
        "CD Nacional": "Nacional",
        "CD Santa Clara": "Santa Clara",
        "CD Tondela": "Tondela",
        "CF Estrela da Amadora": "Estrela",
        "CS Marítimo": "Maritimo",
        "Casa Pia AC": "Casa Pia",
        "FC Alverca": "Alverca",
        "FC Arouca": "Arouca",
        "FC Famalicão": "Famalicao",
        "FC Porto": "Porto",
        "GD Estoril Praia": "Estoril",
        "Gil Vicente FC": "Gil Vicente",
        "Moreirense FC": "Moreirense",
        "Rio Ave FC": "Rio Ave",
        "Sport Lisboa e Benfica": "Benfica",
        "Sporting Clube de Braga": "Sp Braga",
        "Sporting Clube de Portugal": "Sp Lisbon",
        "Vitória SC": "Guimaraes",
    },
    # 巴甲（BSA → BRA，自然年赛季）
    "BRA": {
        "Botafogo FR": "Botafogo RJ",
        "CA Mineiro": "Atletico-MG",
        "CA Paranaense": "Athletico-PR",
        "CR Flamengo": "Flamengo RJ",
        "CR Vasco da Gama": "Vasco",
        "Chapecoense AF": "Chapecoense-SC",
        "Clube do Remo": "Remo",
        "Coritiba FBC": "Coritiba",
        "Cruzeiro EC": "Cruzeiro",
        "EC Bahia": "Bahia",
        "EC Vitória": "Vitoria",
        "Fluminense FC": "Fluminense",
        "Grêmio FBPA": "Gremio",
        "Mirassol FC": "Mirassol",
        "RB Bragantino": "Bragantino",
        "SC Corinthians Paulista": "Corinthians",
        "SC Internacional": "Internacional",
        "SE Palmeiras": "Palmeiras",
        "Santos FC": "Santos",
        "São Paulo FC": "Sao Paulo",
    },
}
