# -*- coding: utf-8 -*-
"""
team_aliases.py — API-Football 队名 → football-data.co.uk 队名 显式映射表

用途：update_scores.py 快速通道把 API-Football 的队名（如 "Manchester United"）
翻译成网站沿用的 football-data.co.uk 短名（如 "Man United"），保证同一场比赛在
football_latest.json 里只有一条记录（去重键 date|team1|team2 一致）。

结构：{ 本站联赛码: { API-Football 队名: football-data.co.uk 队名 } }
联赛码 → API-Football league.id 的对应关系在 update_scores.py 的 APIFB_LEAGUES。

生成方式（2026-08）：API-Football /teams（2024 赛季，免费版可查的最新赛季）+ 实测
fixtures 队名，与 data/{code}.js 历史队名池 + football_latest.json 当前队名做归一化
自动匹配（99%），少数知名差异人工核对补丁。运行中出现「队名未映射，跳过」警告时，
把警告里的 API-Football 原名和对应 co.uk 短名按本表格式补进来即可。
"""

TEAM_ALIASES = {

    # 英超（E0）
    "E0": {
        "Arsenal": "Arsenal",
        "Aston Villa": "Aston Villa",
        "Bournemouth": "Bournemouth",
        "Brentford": "Brentford",
        "Brighton": "Brighton",
        "Chelsea": "Chelsea",
        "Crystal Palace": "Crystal Palace",
        "Everton": "Everton",
        "Fulham": "Fulham",
        "Ipswich": "Ipswich",
        "Leicester": "Leicester",
        "Liverpool": "Liverpool",
        "Manchester City": "Man City",
        "Manchester United": "Man United",
        "Newcastle": "Newcastle",
        "Nottingham Forest": "Nott'm Forest",
        "Southampton": "Southampton",
        "Tottenham": "Tottenham",
        "West Ham": "West Ham",
        "Wolves": "Wolves",
    },
    # 英冠（E1）
    "E1": {
        "Blackburn": "Blackburn",
        "Bristol City": "Bristol City",
        "Burnley": "Burnley",
        "Cardiff": "Cardiff",
        "Coventry": "Coventry",
        "Derby": "Derby",
        "Hull City": "Hull",
        "Leeds": "Leeds",
        "Luton": "Luton",
        "Middlesbrough": "Middlesbrough",
        "Millwall": "Millwall",
        "Norwich": "Norwich",
        "Oxford United": "Oxford",
        "Plymouth": "Plymouth",
        "Portsmouth": "Portsmouth",
        "Preston": "Preston",
        "QPR": "QPR",
        "Sheffield Utd": "Sheffield United",
        "Sheffield Wednesday": "Sheffield Weds",
        "Stoke City": "Stoke",
        "Sunderland": "Sunderland",
        "Swansea": "Swansea",
        "Watford": "Watford",
        "West Brom": "West Brom",
    },
    # 英甲（E2）
    "E2": {
        "Barnsley": "Barnsley",
        "Birmingham": "Birmingham",
        "Blackpool": "Blackpool",
        "Bolton": "Bolton",
        "Bristol Rovers": "Bristol Rvs",
        "Burton Albion": "Burton",
        "Cambridge United": "Cambridge",
        "Charlton": "Charlton",
        "Crawley Town": "Crawley Town",
        "Exeter City": "Exeter",
        "Huddersfield": "Huddersfield",
        "Leyton Orient": "Leyton Orient",
        "Lincoln": "Lincoln",
        "Mansfield Town": "Mansfield",
        "Northampton": "Northampton",
        "Peterborough": "Peterboro",
        "Reading": "Reading",
        "Rotherham": "Rotherham",
        "Shrewsbury": "Shrewsbury",
        "Stevenage": "Stevenage",
        "Stockport County": "Stockport",
        "Wigan": "Wigan",
        "Wrexham": "Wrexham",
        "Wycombe": "Wycombe",
    },
    # 英乙（E3）
    "E3": {
        "AFC Wimbledon": "AFC Wimbledon",
        "Accrington ST": "Accrington",
        "Barrow": "Barrow",
        "Bradford": "Bradford",
        "Bromley": "Bromley",
        "Carlisle": "Carlisle",
        "Cheltenham": "Cheltenham",
        "Chesterfield": "Chesterfield",
        "Colchester": "Colchester",
        "Crewe": "Crewe",
        "Doncaster": "Doncaster",
        "Fleetwood Town": "Fleetwood Town",
        "Gillingham": "Gillingham",
        "Grimsby": "Grimsby",
        "Harrogate Town": "Harrogate",
        "Milton Keynes Dons": "Milton Keynes Dons",
        "Morecambe": "Morecambe",
        "Newport County": "Newport County",
        "Notts County": "Notts County",
        "Port Vale": "Port Vale",
        "Salford City": "Salford",
        "Swindon Town": "Swindon",
        "Tranmere": "Tranmere",
        "Walsall": "Walsall",
    },
    # 英议联（EC）
    "EC": {
        "AFC Fylde": "Fylde",
        "Aldershot Town": "Aldershot",
        "Altrincham": "Altrincham",
        "Barnet": "Barnet",
        "Boston United": "Boston Utd",
        "Braintree": "Braintree Town",
        "Dagenham & Redbridge": "Dag and Red",
        "Eastleigh": "Eastleigh",
        "Ebbsfleet United": "Ebbsfleet",
        "FC Halifax Town": "Halifax",
        "Forest Green": "Forest Green",
        "Gateshead": "Gateshead",
        "Hartlepool": "Hartlepool",
        "Maidenhead": "Maidenhead",
        "Oldham": "Oldham",
        "Rochdale": "Rochdale",
        "Solihull Moors": "Solihull",
        "Southend": "Southend",
        "Sutton Utd": "Sutton",
        "Tamworth": "Tamworth",
        "Wealdstone": "Wealdstone",
        "Woking": "Woking",
        "Yeovil Town": "Yeovil",
        "York": "York",
    },
    # 西甲（SP1）
    "SP1": {
        "Alaves": "Alaves",
        "Athletic Club": "Ath Bilbao",
        "Atletico Madrid": "Ath Madrid",
        "Barcelona": "Barcelona",
        "Celta Vigo": "Celta",
        "Espanyol": "Espanol",
        "Getafe": "Getafe",
        "Girona": "Girona",
        "Las Palmas": "Las Palmas",
        "Leganes": "Leganes",
        "Mallorca": "Mallorca",
        "Osasuna": "Osasuna",
        "Rayo Vallecano": "Vallecano",
        "Real Betis": "Betis",
        "Real Madrid": "Real Madrid",
        "Real Sociedad": "Sociedad",
        "Sevilla": "Sevilla",
        "Valencia": "Valencia",
        "Valladolid": "Valladolid",
        "Villarreal": "Villarreal",
    },
    # 西乙（SP2）
    "SP2": {
        "Albacete": "Albacete",
        "Almeria": "Almeria",
        "Burgos": "Burgos",
        "Cadiz": "Cadiz",
        "Castellón": "Castellon",
        "Cordoba": "Cordoba",
        "Deportivo La Coruna": "La Coruna",
        "Eibar": "Eibar",
        "Elche": "Elche",
        "Eldense": "Eldense",
        "FC Cartagena": "Cartagena",
        "Granada CF": "Granada",
        "Huesca": "Huesca",
        "Levante": "Levante",
        "Malaga": "Malaga",
        "Mirandes": "Mirandes",
        "Oviedo": "Oviedo",
        "Racing Ferrol": "Ferrol",
        "Racing Santander": "Santander",
        "Sporting Gijon": "Sp Gijon",
        "Tenerife": "Tenerife",
        "Zaragoza": "Zaragoza",
    },
    # 德甲（D1）
    "D1": {
        "1. FC Heidenheim": "Heidenheim",
        "1899 Hoffenheim": "Hoffenheim",
        "Bayer Leverkusen": "Leverkusen",
        "Bayern München": "Bayern Munich",
        "Borussia Dortmund": "Dortmund",
        "Borussia Mönchengladbach": "M'gladbach",
        "Eintracht Frankfurt": "Ein Frankfurt",
        "FC Augsburg": "Augsburg",
        "FC St. Pauli": "St Pauli",
        "FSV Mainz 05": "Mainz",
        "Holstein Kiel": "Holstein Kiel",
        "RB Leipzig": "RB Leipzig",
        "SC Freiburg": "Freiburg",
        "Union Berlin": "Union Berlin",
        "VfB Stuttgart": "Stuttgart",
        "VfL Bochum": "Bochum",
        "VfL Wolfsburg": "Wolfsburg",
        "Werder Bremen": "Werder Bremen",
    },
    # 德乙（D2）
    "D2": {
        "1. FC Kaiserslautern": "Kaiserslautern",
        "1. FC Köln": "FC Koln",
        "1. FC Magdeburg": "Magdeburg",
        "1. FC Nürnberg": "Nurnberg",
        "Eintracht Braunschweig": "Braunschweig",
        "FC Schalke 04": "Schalke 04",
        "Fortuna Düsseldorf": "Fortuna Dusseldorf",
        "Hamburger SV": "Hamburg",
        "Hannover 96": "Hannover",
        "Hertha BSC": "Hertha",
        "Karlsruher SC": "Karlsruhe",
        "Preußen Münster": "Preußen Münster",
        "SC Paderborn 07": "Paderborn",
        "SSV Jahn Regensburg": "Regensburg",
        "SSV Ulm 1846": "Ulm",
        "SV Darmstadt 98": "Darmstadt",
        "SV Elversberg": "Elversberg",
        "SpVgg Greuther Fürth": "Greuther Furth",
    },
    # 意甲（I1）
    "I1": {
        "AC Milan": "Milan",
        "AS Roma": "Roma",
        "Atalanta": "Atalanta",
        "Bologna": "Bologna",
        "Cagliari": "Cagliari",
        "Como": "Como",
        "Empoli": "Empoli",
        "Fiorentina": "Fiorentina",
        "Genoa": "Genoa",
        "Hellas Verona": "Verona",
        "Inter": "Inter",
        "Juventus": "Juventus",
        "Lazio": "Lazio",
        "Lecce": "Lecce",
        "Monza": "Monza",
        "Napoli": "Napoli",
        "Parma": "Parma",
        "Torino": "Torino",
        "Udinese": "Udinese",
        "Venezia": "Venezia",
    },
    # 意乙（I2）
    "I2": {
        "Bari": "Bari",
        "Brescia": "Brescia",
        "Carrarese": "Carrarese",
        "Catanzaro": "Catanzaro",
        "Cesena": "Cesena",
        "Cittadella": "Cittadella",
        "Cosenza": "Cosenza",
        "Cremonese": "Cremonese",
        "Frosinone": "Frosinone",
        "Juve Stabia": "Juve Stabia",
        "Mantova": "Mantova",
        "Modena": "Modena",
        "Palermo": "Palermo",
        "Pisa": "Pisa",
        "Reggiana": "Reggiana",
        "Salernitana": "Salernitana",
        "Sampdoria": "Sampdoria",
        "Sassuolo": "Sassuolo",
        "Spezia": "Spezia",
        "Sudtirol": "Sudtirol",
    },
    # 法甲（F1）
    "F1": {
        "Angers": "Angers",
        "Auxerre": "Auxerre",
        "Le Havre": "Le Havre",
        "Lens": "Lens",
        "Lille": "Lille",
        "Lyon": "Lyon",
        "Marseille": "Marseille",
        "Metz": "Metz",
        "Monaco": "Monaco",
        "Montpellier": "Montpellier",
        "Nantes": "Nantes",
        "Nice": "Nice",
        "Paris Saint Germain": "Paris SG",
        "Reims": "Reims",
        "Rennes": "Rennes",
        "Saint Etienne": "St Etienne",
        "Stade Brestois 29": "Brest",
        "Strasbourg": "Strasbourg",
        "Toulouse": "Toulouse",
    },
    # 法乙（F2）
    "F2": {
        "Ajaccio": "Ajaccio",
        "Amiens": "Amiens",
        "Annecy": "Annecy",
        "Bastia": "Bastia",
        "Boulogne": "Boulogne",
        "Caen": "Caen",
        "Clermont Foot": "Clermont",
        "Dunkerque": "Dunkerque",
        "Estac Troyes": "Troyes",
        "Grenoble": "Grenoble",
        "Guingamp": "Guingamp",
        "Laval": "Laval",
        "Lorient": "Lorient",
        "Martigues": "Martigues",
        "Metz": "Metz",
        "PAU": "Pau FC",
        "Paris FC": "Paris FC",
        "RED Star FC 93": "Red Star",
        "Rodez": "Rodez",
    },
    # 苏超（SC0）
    "SC0": {
        "Aberdeen": "Aberdeen",
        "Celtic": "Celtic",
        "Dundee": "Dundee",
        "Dundee Utd": "Dundee",
        "Heart Of Midlothian": "Hearts",
        "Hibernian": "Hibernian",
        "Kilmarnock": "Kilmarnock",
        "Livingston": "Livingston",
        "Motherwell": "Motherwell",
        "Partick": "Partick",
        "Rangers": "Rangers",
        "Ross County": "Ross County",
        "ST Johnstone": "St Johnstone",
        "ST Mirren": "St Mirren",
    },
    # 苏冠（SC1）
    "SC1": {
        "Airdrie United": "Airdrie Utd",
        "Ayr Utd": "Ayr",
        "Cove Rangers": "Cove Rangers",
        "Dunfermline": "Dunfermline",
        "Falkirk": "Falkirk",
        "Hamilton Academical": "Hamilton",
        "Livingston": "Livingston",
        "Morton": "Morton",
        "Partick": "Partick",
        "Queen of the South": "Queen of Sth",
        "Queen's Park": "Queens Park",
        "Raith Rovers": "Raith Rvs",
        "Stenhousemuir": "Stenhousemuir",
    },
    # 苏甲（SC2）
    "SC2": {
        "Alloa Athletic": "Alloa",
        "Annan Athletic": "Annan Athletic",
        "Arbroath": "Arbroath",
        "Cove Rangers": "Cove Rangers",
        "Dumbarton": "Dumbarton",
        "East Fife": "East Fife",
        "Edinburgh City": "Edinburgh City",
        "Inverness CT": "Inverness C",
        "Kelty Hearts": "Kelty Hearts",
        "Montrose": "Montrose",
        "Queen of the South": "Queen of Sth",
        "Stenhousemuir": "Stenhousemuir",
    },
    # 苏乙（SC3）
    "SC3": {
        "Bonnyrigg Rose Athletic": "Bonnyrigg Rose",
        "Clyde": "Clyde",
        "East Fife": "East Fife",
        "East Kilbride": "East Kilbride",
        "Edinburgh City": "Edinburgh City",
        "Elgin City": "Elgin",
        "Forfar Athletic": "Forfar",
        "Peterhead": "Peterhead",
        "Spartans": "Spartans",
        "Stirling Albion": "Stirling",
        "Stranraer": "Stranraer",
    },
    # 荷甲（N1）
    "N1": {
        "ADO Den Haag": "Den Haag",
        "AZ Alkmaar": "AZ Alkmaar",
        "Ajax": "Ajax",
        "Almere City FC": "Almere City",
        "Cambuur": "Cambuur",
        "De Graafschap": "Graafschap",
        "Dordrecht": "Dordrecht",
        "Feyenoord": "Feyenoord",
        "Fortuna Sittard": "For Sittard",
        "GO Ahead Eagles": "Go Ahead Eagles",
        "Groningen": "Groningen",
        "Heerenveen": "Heerenveen",
        "Heracles": "Heracles",
        "NAC Breda": "NAC Breda",
        "NEC Nijmegen": "Nijmegen",
        "PEC Zwolle": "Zwolle",
        "PSV Eindhoven": "PSV Eindhoven",
        "Sparta Rotterdam": "Sparta Rotterdam",
        "Telstar": "Telstar",
        "Twente": "Twente",
        "Utrecht": "Utrecht",
        "Waalwijk": "Waalwijk",
        "Willem II": "Willem II",
    },
    # 比甲（B1）
    "B1": {
        "Anderlecht": "Anderlecht",
        "Antwerp": "Antwerp",
        "Beerschot VA": "Beerschot VA",
        "Cercle Brugge": "Cercle Brugge",
        "Charleroi": "Charleroi",
        "Club Brugge KV": "Club Brugge",
        "Dender": "Dender",
        "Genk": "Genk",
        "Gent": "Gent",
        "KV Mechelen": "Mechelen",
        "KVC Westerlo": "Westerlo",
        "Kortrijk": "Kortrijk",
        "OH Leuven": "Oud-Heverlee Leuven",
        "St. Truiden": "St Truiden",
        "Standard Liege": "Standard",
        "Union St. Gilloise": "St. Gilloise",
    },
    # 葡超（P1）
    "P1": {
        "Nacional": "Nacional",
        "Santa Clara": "Santa Clara",
    },
    # 土超（T1）
    "T1": {
        "Adana Demirspor": "Ad. Demirspor",
        "Alanyaspor": "Alanyaspor",
        "Antalyaspor": "Antalyaspor",
        "Başakşehir": "Buyuksehyr",
        "Beşiktaş": "Besiktas",
        "Bodrum FK": "Bodrumspor",
        "Eyüpspor": "Eyupspor",
        "Fenerbahçe": "Fenerbahce",
        "Galatasaray": "Galatasaray",
        "Gaziantep FK": "Gaziantep",
        "Göztepe": "Goztep",
        "Hatayspor": "Hatayspor",
        "Kasımpaşa": "Kasimpasa",
        "Kayserispor": "Kayserispor",
        "Konyaspor": "Konyaspor",
        "Rizespor": "Rizespor",
        "Samsunspor": "Samsunspor",
        "Sivasspor": "Sivasspor",
        "Trabzonspor": "Trabzonspor",
    },
    # 希腊超（G1）
    "G1": {
        "AEK Athens FC": "AEK",
        "Aris Thessalonikis": "Aris",
        "Asteras Tripolis": "Asteras Tripolis",
        "Atromitos": "Atromitos",
        "Kallithea": "Athens Kallithea",
        "Lamia": "Lamia",
        "Levadiakos": "Levadeiakos",
        "OFI": "OFI",
        "Olympiakos Piraeus": "Olympiakos",
        "PAOK": "PAOK",
        "Panathinaikos": "Panathinaikos",
        "Panetolikos": "Panetolikos",
        "Panserraikos": "Panserraikos",
        "Volos NFC": "Volos NFC",
    },
    # 阿甲（ARG）
    "ARG": {
        "Banfield": "Banfield",
        "Belgrano Cordoba": "Belgrano",
        "Central Cordoba de Santiago": "Central Cordoba",
        "Union Santa Fe": "Union de Santa Fe",
    },
    # 奥甲（AUT）
    "AUT": {
        "Austria Klagenfurt": "A. Klagenfurt",
        "Austria Vienna": "Austria Vienna",
        "FC BW Linz": "BW Linz",
        "Grazer AK": "Grazer AK",
        "Lask Linz": "LASK",
        "Rapid Vienna": "SK Rapid",
        "Red Bull Salzburg": "Salzburg",
        "SCR Altach": "Altach",
        "Sturm Graz": "Sturm Graz",
        "TSV Hartberg": "Hartberg",
        "WSG Wattens": "Tirol",
        "Wolfsberger AC": "Wolfsberger AC",
    },
    # 巴甲（BRA）
    "BRA": {
        "Atletico Goianiense": "Atletico GO",
        "Atletico Paranaense": "Athletico-PR",
        "Atletico-MG": "Atletico-MG",
        "Bahia": "Bahia",
        "Botafogo": "Botafogo RJ",
        "Corinthians": "Corinthians",
        "Criciuma": "Criciuma",
        "Cruzeiro": "Cruzeiro",
        "Cuiaba": "Cuiaba",
        "Flamengo": "Flamengo RJ",
        "Fluminense": "Fluminense",
        "Fortaleza EC": "Fortaleza",
        "Gremio": "Gremio",
        "Internacional": "Internacional",
        "Juventude": "Juventude",
        "Palmeiras": "Palmeiras",
        "RB Bragantino": "Bragantino",
        "Sao Paulo": "Sao Paulo",
        "Vasco DA Gama": "Vasco",
        "Vitoria": "Vitoria",
    },
    # 中超（CHN）
    "CHN": {
        "Beijing Guoan": "Beijing Guoan",
        "Changchun Yatai": "Changchun Yatai",
        "Chengdu Better City": "Chengdu Rongcheng",
        "Hangzhou Greentown": "Hangzhou Greentown",
        "Henan Jianye": "Henan Songshan Longmen",
        "Meizhou Kejia": "Meizhou Hakka",
        "Nantong Zhiyun": "Nantong Zhiyun",
        "Qingdao Jonoon": "Qingdao FC",
        "Qingdao Youth Island": "Qingdao FC",
        "SHANGHAI SIPG": "Shanghai SIPG",
        "Shandong Luneng": "Shandong Luneng",
        "Shanghai Shenhua": "Shanghai Shenhua",
        "Shijiazhuang Y. J.": "Shijiazhuang",
        "Sichuan Jiuniu": "Shenzhen Xinpengcheng",
        "Tianjin Teda": "Tianjin Jinmen Tiger",
        "Wuhan Three Towns": "Wuhan Three Towns",
    },
    # 丹麦超（DNK）
    "DNK": {
        "Odense": "Odense",
        "Silkeborg": "Silkeborg",
    },
    # 芬超（FIN）
    "FIN": {
        "AC Oulu": "AC Oulu",
        "EIF": "Ekenas",
        "FF Jaro": "Jaro",
        "Gnistan": "Gnistan",
        "HJK Helsinki": "HJK",
        "Haka": "Haka",
        "Ilves": "Ilves",
        "Inter Turku": "Inter Turku",
        "KuPS": "KuPS",
        "Lahti": "Lahti",
        "Mariehamn": "Mariehamn",
        "SJK": "SJK",
        "VPS": "VPS",
    },
    # 爱超（IRL）
    "IRL": {
        "Bohemians": "Bohemians",
        "Bray Wanderers": "Bray",
        "Derry City": "Derry City",
        "Drogheda United": "Drogheda",
        "Dundalk": "Dundalk",
        "Galway United": "Galway",
        "Shamrock Rovers": "Shamrock Rovers",
        "Shelbourne": "Shelbourne",
        "Sligo Rovers": "Sligo Rovers",
        "St Patrick's Athl.": "St. Patricks",
        "Waterford": "Waterford",
    },
    # J1（JPN）
    "JPN": {
        "Albirex Niigata": "Albirex Niigata",
        "Avispa Fukuoka": "Avispa Fukuoka",
        "Cerezo Osaka": "Cerezo Osaka",
        "Consadole Sapporo": "Hokkaido Consadole Sapporo",
        "FC Tokyo": "FC Tokyo",
        "Gamba Osaka": "Gamba Osaka",
        "Jubilo Iwata": "Iwata",
        "Kashima": "Kashima Antlers",
        "Kashiwa Reysol": "Kashiwa Reysol",
        "Kawasaki Frontale": "Kawasaki Frontale",
        "Kyoto Sanga": "Kyoto",
        "Machida Zelvia": "Machida",
        "Nagoya Grampus": "Nagoya Grampus",
        "Sagan Tosu": "Sagan Tosu",
        "Sanfrecce Hiroshima": "Sanfrecce Hiroshima",
        "Shonan Bellmare": "Shonan Bellmare",
        "Tokyo Verdy": "FC Tokyo",
        "Urawa": "Urawa Reds",
        "Vissel Kobe": "Vissel Kobe",
        "Yokohama F. Marinos": "Yokohama F. Marinos",
    },
    # 墨超（MEX）
    "MEX": {
        "Atlas": "Atlas",
        "Atletico San Luis": "Atl. San Luis",
        "CF Pachuca": "Pachuca",
        "Club America": "Club America",
        "Club Queretaro": "Queretaro",
        "Club Tijuana": "Club Tijuana",
        "Cruz Azul": "Cruz Azul",
        "FC Juarez": "Juarez",
        "Guadalajara Chivas": "Guadalajara Chivas",
        "Leon": "Club Leon",
        "Mazatlán": "Mazatlan FC",
        "Monterrey": "Monterrey",
        "Necaxa": "Necaxa",
        "Puebla": "Puebla",
        "Santos Laguna": "Santos Laguna",
        "Tigres UANL": "Tigres UANL",
        "Toluca": "Toluca",
        "U.N.A.M. - Pumas": "UNAM Pumas",
    },
    # 挪超（NOR）
    "NOR": {
        "Bodo/Glimt": "Bodo/Glimt",
        "Brann": "Brann",
        "Fredrikstad": "Fredrikstad",
        "Ham-Kam": "Ham-Kam",
        "Haugesund": "Haugesund",
        "KFUM Oslo": "KFUM Oslo",
        "Kristiansund BK": "Kristiansund",
        "Lillestrom": "Lillestrom",
        "Molde": "Molde",
        "Moss": "Moss",
        "ODD Ballklubb": "Odd",
        "Rosenborg": "Rosenborg",
        "Sandefjord": "Sandefjord",
        "Sarpsborg 08 FF": "Sarpsborg 08",
        "Stromsgodset": "Stromsgodset",
        "Tromso": "Tromso",
        "Viking": "Viking",
    },
    # 波兰甲（POL）
    "POL": {
        "Cracovia Krakow": "Cracovia",
        "GKS Katowice": "GKS Katowice",
        "Gornik Zabrze": "Gornik Zabrze",
        "Jagiellonia": "Jagiellonia",
        "Korona Kielce": "Korona Kielce",
        "Lech Poznan": "Lech Poznan",
        "Lechia Gdansk": "Lechia Gdansk",
        "Legia Warszawa": "Legia",
        "Motor Lublin": "Motor Lublin",
        "Piast Gliwice": "Piast Gliwice",
        "Pogon Szczecin": "Pogon Szczecin",
        "Puszcza Niepołomice": "Puszcza",
        "Radomiak Radom": "Radomiak Radom",
        "Raków Częstochowa": "Rakow",
        "Slask Wroclaw": "Slask Wroclaw",
        "Stal Mielec": "Stal Mielec",
        "Widzew Łódź": "Widzew Lodz",
        "Zaglebie Lubin": "Zaglebie",
    },
    # 罗甲（ROU）
    "ROU": {
        "Corvinul Hunedoara": "Corvinul",
        "FC Botosani": "FC Botosani",
        "FCSB": "FCSB",
        "Sepsi OSK Sfantu Gheorghe": "Sepsi Sf. Gheorghe",
    },
    # 俄超（RUS）
    "RUS": {
        "Akhmat": "Akhmat Grozny",
        "Fakel": "Fakel Voronezh",
    },
    # 瑞典超（SWE）
    "SWE": {
        "Djurgardens IF": "Djurgarden",
        "IF Brommapojkarna": "Brommapojkarna",
        "Sirius": "Sirius",
        "Vasteras SK FK": "Vasteras SK",
    },
    # 瑞士超（SWZ）
    "SWZ": {
        "BSC Young Boys": "Young Boys",
        "FC Aarau": "Aarau",
        "FC Basel 1893": "Basel",
        "FC Lugano": "Lugano",
        "FC Luzern": "Luzern",
        "FC ST. Gallen": "St. Gallen",
        "FC Sion": "Sion",
        "FC Winterthur": "Winterthur",
        "FC Zurich": "Zurich",
        "Grasshoppers": "Grasshoppers",
        "Lausanne": "Lausanne",
        "Servette FC": "Servette",
        "Yverdon Sport": "Yverdon",
    },
    # MLS（USA）
    "USA": {
        "Atlanta United FC": "Atlanta Utd",
        "Austin": "Austin FC",
        "CF Montreal": "CF Montreal",
        "Charlotte": "Charlotte",
        "Chicago Fire": "Chicago Fire",
        "Colorado Rapids": "Colorado Rapids",
        "Columbus Crew": "Columbus Crew",
        "DC United": "DC United",
        "FC Cincinnati": "FC Cincinnati",
        "FC Dallas": "FC Dallas",
        "Houston Dynamo": "Houston Dynamo",
        "Inter Miami": "Inter Miami",
        "Los Angeles FC": "Los Angeles FC",
        "Los Angeles Galaxy": "Los Angeles Galaxy",
        "Minnesota United FC": "Minnesota United",
        "Nashville SC": "Nashville SC",
        "New England Revolution": "New England Revolution",
        "New York City FC": "New York City",
        "New York Red Bulls": "New York Red Bulls",
        "Orlando City SC": "Orlando City",
        "Philadelphia Union": "Philadelphia Union",
        "Portland Timbers": "Portland Timbers",
        "Real Salt Lake": "Real Salt Lake",
        "San Jose Earthquakes": "San Jose Earthquakes",
        "Seattle Sounders": "Seattle Sounders",
        "Sporting Kansas City": "Sporting Kansas City",
        "St. Louis City": "St. Louis City",
        "Toronto FC": "Toronto FC",
        "Vancouver Whitecaps": "Vancouver Whitecaps",
    },
}
