# -*- coding: utf-8 -*-
"""team_aliases.py — API-Football 官方队名 → football-data.co.uk 短名。
由 rebuild_aliases.py 基于 Pro /teams 当前赛季名单重建；未映射球队整场跳过。
"""

TEAM_ALIASES = {
    # E0
    'E0': {
        'Arsenal': 'Arsenal',
        'Aston Villa': 'Aston Villa',
        'Bournemouth': 'Bournemouth',
        'Brentford': 'Brentford',
        'Brighton': 'Brighton',
        'Chelsea': 'Chelsea',
        'Coventry': 'Coventry',
        'Crystal Palace': 'Crystal Palace',
        'Everton': 'Everton',
        'Fulham': 'Fulham',
        'Hull City': 'Hull',
        'Ipswich': 'Ipswich',
        'Leeds': 'Leeds',
        'Leicester': 'Leicester',
        'Liverpool': 'Liverpool',
        'Manchester City': 'Man City',
        'Manchester United': 'Man United',
        'Newcastle': 'Newcastle',
        'Nottingham Forest': "Nott'm Forest",
        'Southampton': 'Southampton',
        'Sunderland': 'Sunderland',
        'Tottenham': 'Tottenham',
        'West Ham': 'West Ham',
        'Wolves': 'Wolves',
    },
    # SP1
    'SP1': {
        'Alaves': 'Alaves',
        'Athletic Club': 'Ath Bilbao',
        'Atletico Madrid': 'Ath Madrid',
        'Barcelona': 'Barcelona',
        'Celta Vigo': 'Celta',
        'Deportivo La Coruna': 'La Coruna',
        'Elche': 'Elche',
        'Espanyol': 'Espanol',
        'Getafe': 'Getafe',
        'Girona': 'Girona',
        'Las Palmas': 'Las Palmas',
        'Leganes': 'Leganes',
        'Levante': 'Levante',
        'Malaga': 'Malaga',
        'Mallorca': 'Mallorca',
        'Osasuna': 'Osasuna',
        'Racing Santander': 'Racing Santander',
        'Rayo Vallecano': 'Vallecano',
        'Real Betis': 'Betis',
        'Real Madrid': 'Real Madrid',
        'Real Sociedad': 'Sociedad',
        'Sevilla': 'Sevilla',
        'Valencia': 'Valencia',
        'Valladolid': 'Valladolid',
        'Villarreal': 'Villarreal',
    },
    # D1
    'D1': {
        '1. FC Heidenheim': 'Heidenheim',
        '1. FC Köln': 'FC Koln',
        '1899 Hoffenheim': 'Hoffenheim',
        'Bayer Leverkusen': 'Leverkusen',
        'Bayern München': 'Bayern Munich',
        'Borussia Dortmund': 'Dortmund',
        'Borussia Mönchengladbach': "M'gladbach",
        'Eintracht Frankfurt': 'Ein Frankfurt',
        'FC Augsburg': 'Augsburg',
        'FC Schalke 04': 'Schalke 04',
        'FC St. Pauli': 'St Pauli',
        'FSV Mainz 05': 'Mainz',
        'Hamburger SV': 'Hamburger SV',
        'Holstein Kiel': 'Holstein Kiel',
        'RB Leipzig': 'RB Leipzig',
        'SC Freiburg': 'Freiburg',
        'SC Paderborn 07': 'Paderborn',
        'SV Elversberg': 'Elversberg',
        'Union Berlin': 'Union Berlin',
        'VfB Stuttgart': 'Stuttgart',
        'VfL Bochum': 'Bochum',
        'VfL Wolfsburg': 'Wolfsburg',
        'Werder Bremen': 'Werder Bremen',
    },
    # I1
    'I1': {
        'AC Milan': 'Milan',
        'AS Roma': 'Roma',
        'Atalanta': 'Atalanta',
        'Bologna': 'Bologna',
        'Cagliari': 'Cagliari',
        'Como': 'Como',
        'Empoli': 'Empoli',
        'Fiorentina': 'Fiorentina',
        'Frosinone': 'Frosinone',
        'Genoa': 'Genoa',
        'Hellas Verona': 'Verona',
        'Inter': 'Inter',
        'Juventus': 'Juventus',
        'Lazio': 'Lazio',
        'Lecce': 'Lecce',
        'Monza': 'Monza',
        'Napoli': 'Napoli',
        'Parma': 'Parma',
        'Sassuolo': 'Sassuolo',
        'Torino': 'Torino',
        'Udinese': 'Udinese',
        'Venezia': 'Venezia',
    },
    # F1
    'F1': {
        'Angers': 'Angers',
        'Auxerre': 'Auxerre',
        'Estac Troyes': 'Troyes',
        'Le Havre': 'Le Havre',
        'Le Mans': 'Le Mans',
        'Lens': 'Lens',
        'Lille': 'Lille',
        'Lorient': 'Lorient',
        'Lyon': 'Lyon',
        'Marseille': 'Marseille',
        'Metz': 'Metz',
        'Monaco': 'Monaco',
        'Montpellier': 'Montpellier',
        'Nantes': 'Nantes',
        'Nice': 'Nice',
        'Paris FC': 'Paris FC',
        'Paris Saint Germain': 'Paris SG',
        'Reims': 'Reims',
        'Rennes': 'Rennes',
        'Saint Etienne': 'St Etienne',
        'Stade Brestois 29': 'Brest',
        'Strasbourg': 'Strasbourg',
        'Toulouse': 'Toulouse',
    },
    # E1
    'E1': {
        'Birmingham': 'Birmingham',
        'Blackburn': 'Blackburn',
        'Bolton': 'Bolton',
        'Bristol City': 'Bristol City',
        'Burnley': 'Burnley',
        'Cardiff': 'Cardiff',
        'Charlton': 'Charlton',
        'Coventry': 'Coventry',
        'Derby': 'Derby',
        'Hull City': 'Hull',
        'Leeds': 'Leeds',
        'Lincoln': 'Lincoln',
        'Luton': 'Luton',
        'Middlesbrough': 'Middlesbrough',
        'Millwall': 'Millwall',
        'Norwich': 'Norwich',
        'Oxford United': 'Oxford',
        'Plymouth': 'Plymouth',
        'Portsmouth': 'Portsmouth',
        'Preston': 'Preston',
        'QPR': 'QPR',
        'Sheffield Utd': 'Sheffield United',
        'Sheffield Wednesday': 'Sheffield Weds',
        'Southampton': 'Southampton',
        'Stoke City': 'Stoke',
        'Sunderland': 'Sunderland',
        'Swansea': 'Swansea',
        'Watford': 'Watford',
        'West Brom': 'West Brom',
        'West Ham': 'West Ham',
        'Wolves': 'Wolves',
        'Wrexham': 'Wrexham',
    },
    # E2
    'E2': {
        'AFC Wimbledon': 'AFC Wimbledon',
        'Barnsley': 'Barnsley',
        'Birmingham': 'Birmingham',
        'Blackpool': 'Blackpool',
        'Bolton': 'Bolton',
        'Bradford': 'Bradford',
        'Bristol Rovers': 'Bristol Rvs',
        'Bromley': 'Bromley',
        'Burton Albion': 'Burton',
        'Cambridge United': 'Cambridge',
        'Charlton': 'Charlton',
        'Crawley Town': 'Crawley Town',
        'Doncaster': 'Doncaster',
        'Exeter City': 'Exeter',
        'Huddersfield': 'Huddersfield',
        'Leicester': 'Leicester',
        'Leyton Orient': 'Leyton Orient',
        'Lincoln': 'Lincoln',
        'Luton': 'Luton',
        'Mansfield Town': 'Mansfield',
        'Milton Keynes Dons': 'Milton Keynes Dons',
        'Northampton': 'Northampton',
        'Notts County': 'Notts County',
        'Oxford United': 'Oxford',
        'Peterborough': 'Peterboro',
        'Plymouth': 'Plymouth',
        'Reading': 'Reading',
        'Rotherham': 'Rotherham',
        'Sheffield Wednesday': 'Sheffield Weds',
        'Shrewsbury': 'Shrewsbury',
        'Stevenage': 'Stevenage',
        'Stockport County': 'Stockport',
        'Wigan': 'Wigan',
        'Wrexham': 'Wrexham',
        'Wycombe': 'Wycombe',
    },
    # E3
    'E3': {
        'AFC Wimbledon': 'AFC Wimbledon',
        'Accrington ST': 'Accrington',
        'Barnet': 'Barnet',
        'Barrow': 'Barrow',
        'Bradford': 'Bradford',
        'Bristol Rovers': 'Bristol Rvs',
        'Bromley': 'Bromley',
        'Carlisle': 'Carlisle',
        'Cheltenham': 'Cheltenham',
        'Chesterfield': 'Chesterfield',
        'Colchester': 'Colchester',
        'Crawley Town': 'Crawley Town',
        'Crewe': 'Crewe',
        'Doncaster': 'Doncaster',
        'Exeter City': 'Exeter',
        'Fleetwood Town': 'Fleetwood Town',
        'Gillingham': 'Gillingham',
        'Grimsby': 'Grimsby',
        'Harrogate Town': 'Harrogate',
        'Milton Keynes Dons': 'Milton Keynes Dons',
        'Morecambe': 'Morecambe',
        'Newport County': 'Newport County',
        'Northampton': 'Northampton',
        'Notts County': 'Notts County',
        'Oldham': 'Oldham',
        'Port Vale': 'Port Vale',
        'Rochdale': 'Rochdale',
        'Rotherham': 'Rotherham',
        'Salford City': 'Salford',
        'Shrewsbury': 'Shrewsbury',
        'Swindon Town': 'Swindon',
        'Tranmere': 'Tranmere',
        'Walsall': 'Walsall',
        'York': 'York',
    },
    # EC
    'EC': {
        'AFC Fylde': 'Fylde',
        'AFC Hornchurch': 'Hornchurch',
        'Aldershot Town': 'Aldershot',
        'Altrincham': 'Altrincham',
        'Barnet': 'Barnet',
        'Barrow': 'Barrow',
        'Boreham Wood': 'Boreham Wood',
        'Boston United': 'Boston Utd',
        'Braintree': 'Braintree Town',
        'Carlisle': 'Carlisle',
        'Dagenham & Redbridge': 'Dag and Red',
        'Eastleigh': 'Eastleigh',
        'Ebbsfleet United': 'Ebbsfleet',
        'FC Halifax Town': 'Halifax',
        'Forest Green': 'Forest Green',
        'Gateshead': 'Gateshead',
        'Harrogate Town': 'Harrogate',
        'Hartlepool': 'Hartlepool',
        'Kidderminster Harriers': 'Kidderminster',
        'Maidenhead': 'Maidenhead',
        'Oldham': 'Oldham',
        'Rochdale': 'Rochdale',
        'Scunthorpe': 'Scunthorpe',
        'Solihull Moors': 'Solihull',
        'Southend': 'Southend',
        'Sutton Utd': 'Sutton',
        'Tamworth': 'Tamworth',
        'Wealdstone': 'Wealdstone',
        'Woking': 'Woking',
        'Worthing': 'Worthing',
        'Yeovil Town': 'Yeovil',
        'York': 'York',
    },
    # SC0
    'SC0': {
        'Aberdeen': 'Aberdeen',
        'Celtic': 'Celtic',
        'Dundee': 'Dundee',
        'Dundee Utd': 'Dundee',
        'Falkirk': 'Falkirk',
        'Heart Of Midlothian': 'Hearts',
        'Hibernian': 'Hibernian',
        'Kilmarnock': 'Kilmarnock',
        'Livingston': 'Livingston',
        'Motherwell': 'Motherwell',
        'Partick': 'Partick',
        'Rangers': 'Rangers',
        'Ross County': 'Ross County',
        'ST Johnstone': 'St Johnstone',
        'ST Mirren': 'St Mirren',
    },
    # SC1
    'SC1': {
        'Airdrie United': 'Airdrie Utd',
        'Arbroath': 'Arbroath',
        'Ayr Utd': 'Ayr',
        'Cove Rangers': 'Cove Rangers',
        'Dunfermline': 'Dunfermline',
        'Falkirk': 'Falkirk',
        'Hamilton Academical': 'Hamilton',
        'Inverness CT': 'Inverness C',
        'Livingston': 'Livingston',
        'Morton': 'Morton',
        'Partick': 'Partick',
        'Queen of the South': 'Queen of Sth',
        "Queen's Park": 'Queens Park',
        'Raith Rovers': 'Raith Rvs',
        'Stenhousemuir': 'Stenhousemuir',
    },
    # SC2
    'SC2': {
        'Airdrie United': 'Airdrie Utd',
        'Alloa Athletic': 'Alloa',
        'Annan Athletic': 'Annan Athletic',
        'Arbroath': 'Arbroath',
        'Cove Rangers': 'Cove Rangers',
        'Dumbarton': 'Dumbarton',
        'East Fife': 'East Fife',
        'East Kilbride': 'East Kilbride',
        'Edinburgh City': 'Edinburgh City',
        'Hamilton Academical': 'Hamilton',
        'Inverness CT': 'Inverness C',
        'Kelty Hearts': 'Kelty Hearts',
        'Montrose': 'Montrose',
        'Peterhead': 'Peterhead',
        'Queen of the South': 'Queen of Sth',
        'Ross County': 'Ross County',
        'Stenhousemuir': 'Stenhousemuir',
    },
    # SC3
    'SC3': {
        'Annan Athletic': 'Annan Athletic',
        'Bonnyrigg Rose Athletic': 'Bonnyrigg Rose',
        'Clyde': 'Clyde',
        'Dumbarton': 'Dumbarton',
        'East Fife': 'East Fife',
        'East Kilbride': 'East Kilbride',
        'Edinburgh City': 'Edinburgh City',
        'Elgin City': 'Elgin',
        'Forfar Athletic': 'Forfar',
        'Kelty Hearts': 'Kelty Hearts',
        'Peterhead': 'Peterhead',
        'Spartans': 'Spartans',
        'Stirling Albion': 'Stirling',
        'Stranraer': 'Stranraer',
    },
    # D2
    'D2': {
        '1. FC Heidenheim': 'Heidenheim',
        '1. FC Kaiserslautern': 'Kaiserslautern',
        '1. FC Köln': 'FC Koln',
        '1. FC Magdeburg': 'Magdeburg',
        '1. FC Nürnberg': 'Nurnberg',
        'Arminia Bielefeld': 'Bielefeld',
        'Dynamo Dresden': 'Dresden',
        'Eintracht Braunschweig': 'Braunschweig',
        'Energie Cottbus': 'Cottbus',
        'FC Schalke 04': 'Schalke 04',
        'FC St. Pauli': 'St Pauli',
        'Fortuna Düsseldorf': 'Fortuna Dusseldorf',
        'Hamburger SV': 'Hamburg',
        'Hannover 96': 'Hannover',
        'Hertha BSC': 'Hertha',
        'Holstein Kiel': 'Holstein Kiel',
        'Karlsruher SC': 'Karlsruhe',
        'Preußen Münster': 'Preußen Münster',
        'SC Paderborn 07': 'Paderborn',
        'SSV Jahn Regensburg': 'Regensburg',
        'SSV Ulm 1846': 'Ulm',
        'SV Darmstadt 98': 'Darmstadt',
        'SV Elversberg': 'Elversberg',
        'SpVgg Greuther Fürth': 'Greuther Furth',
        'VfL Bochum': 'Bochum',
        'VfL Osnabrück': 'Osnabruck',
        'VfL Wolfsburg': 'Wolfsburg',
    },
    # I2
    'I2': {
        'Arezzo': 'Arezzo',
        'Ascoli': 'Ascoli',
        'Avellino': 'Avellino',
        'Bari': 'Bari',
        'Benevento': 'Benevento',
        'Brescia': 'Brescia',
        'Carrarese': 'Carrarese',
        'Catanzaro': 'Catanzaro',
        'Cesena': 'Cesena',
        'Cittadella': 'Cittadella',
        'Cosenza': 'Cosenza',
        'Cremonese': 'Cremonese',
        'Empoli': 'Empoli',
        'Frosinone': 'Frosinone',
        'Hellas Verona': 'Verona',
        'Juve Stabia': 'Juve Stabia',
        'Mantova': 'Mantova',
        'Modena': 'Modena',
        'Padova': 'Padova',
        'Palermo': 'Palermo',
        'Pisa': 'Pisa',
        'Reggiana': 'Reggiana',
        'Salernitana': 'Salernitana',
        'Sampdoria': 'Sampdoria',
        'Sassuolo': 'Sassuolo',
        'Spezia': 'Spezia',
        'Sudtirol': 'Sudtirol',
        'Vicenza Virtus': 'Vicenza',
        'Virtus Entella': 'Virtus Entella',
    },
    # SP2
    'SP2': {
        'AD Ceuta FC': 'Ceuta',
        'Albacete': 'Albacete',
        'Almeria': 'Almeria',
        'Burgos': 'Burgos',
        'Cadiz': 'Cadiz',
        'Castellón': 'Castellon',
        'Celta de Vigo II': 'Celta B',
        'Cordoba': 'Cordoba',
        'Deportivo La Coruna': 'La Coruna',
        'Eibar': 'Eibar',
        'Elche': 'Elche',
        'Eldense': 'Eldense',
        'FC Andorra': 'Andorra',
        'FC Cartagena': 'Cartagena',
        'Girona': 'Girona',
        'Granada CF': 'Granada',
        'Huesca': 'Huesca',
        'Las Palmas': 'Las Palmas',
        'Leganes': 'Leganes',
        'Levante': 'Levante',
        'Malaga': 'Malaga',
        'Mallorca': 'Mallorca',
        'Mirandes': 'Mirandes',
        'Oviedo': 'Oviedo',
        'Racing Ferrol': 'Ferrol',
        'Racing Santander': 'Santander',
        'Real Sociedad II': 'Sociedad B',
        'Sabadell': 'Sabadell',
        'Sporting Gijon': 'Sp Gijon',
        'Tenerife': 'Tenerife',
        'Valladolid': 'Valladolid',
        'Zaragoza': 'Zaragoza',
    },
    # F2
    'F2': {
        'Ajaccio': 'Ajaccio',
        'Amiens': 'Amiens',
        'Annecy': 'Annecy',
        'Bastia': 'Bastia',
        'Boulogne': 'Boulogne',
        'Caen': 'Caen',
        'Clermont Foot': 'Clermont',
        'Dijon': 'Dijon',
        'Dunkerque': 'Dunkerque',
        'Estac Troyes': 'Troyes',
        'Grenoble': 'Grenoble',
        'Guingamp': 'Guingamp',
        'Laval': 'Laval',
        'Lorient': 'Lorient',
        'Martigues': 'Martigues',
        'Metz': 'Metz',
        'Montpellier': 'Montpellier',
        'Nancy': 'Nancy',
        'Nantes': 'Nantes',
        'PAU': 'Pau FC',
        'Paris FC': 'Paris FC',
        'RED Star FC 93': 'Red Star',
        'Reims': 'Reims',
        'Rodez': 'Rodez',
        'Saint Etienne': 'St Etienne',
        'Sochaux': 'Sochaux',
    },
    # N1
    'N1': {
        'ADO Den Haag': 'Den Haag',
        'AZ Alkmaar': 'AZ Alkmaar',
        'Ajax': 'Ajax',
        'Almere City FC': 'Almere City',
        'Cambuur': 'Cambuur',
        'De Graafschap': 'Graafschap',
        'Dordrecht': 'Dordrecht',
        'Excelsior': 'Excelsior',
        'Feyenoord': 'Feyenoord',
        'Fortuna Sittard': 'For Sittard',
        'GO Ahead Eagles': 'Go Ahead Eagles',
        'Groningen': 'Groningen',
        'Heerenveen': 'Heerenveen',
        'Heracles': 'Heracles',
        'NAC Breda': 'NAC Breda',
        'NEC Nijmegen': 'Nijmegen',
        'PEC Zwolle': 'Zwolle',
        'PSV Eindhoven': 'PSV Eindhoven',
        'Sparta Rotterdam': 'Sparta Rotterdam',
        'Telstar': 'Telstar',
        'Twente': 'Twente',
        'Utrecht': 'Utrecht',
        'Waalwijk': 'Waalwijk',
        'Willem II': 'Willem II',
    },
    # B1
    'B1': {
        'Anderlecht': 'Anderlecht',
        'Antwerp': 'Antwerp',
        'Beerschot VA': 'Beerschot VA',
        'Cercle Brugge': 'Cercle Brugge',
        'Charleroi': 'Charleroi',
        'Club Brugge KV': 'Club Brugge',
        'Dender': 'Dender',
        'Genk': 'Genk',
        'Gent': 'Gent',
        'KV Mechelen': 'Mechelen',
        'KVC Westerlo': 'Westerlo',
        'Kortrijk': 'Kortrijk',
        'Lommel United': 'Lommel SK',
        'OH Leuven': 'Oud-Heverlee Leuven',
        'RAAL La Louvière': 'RAAL La Louviere',
        'SK Beveren': 'Beveren',
        'St. Truiden': 'St Truiden',
        'Standard Liege': 'Standard',
        'Union St. Gilloise': 'St. Gilloise',
        'Zulte Waregem': 'Waregem',
    },
    # P1
    'P1': {
        'Academico Viseu': 'Academico Viseu',
        'Alverca': 'Alverca',
        'Arouca': 'Arouca',
        'Benfica': 'Benfica',
        'Casa Pia': 'Casa Pia',
        'Estoril': 'Estoril',
        'Estrela': 'Estrela',
        'FC Porto': 'Porto',
        'Famalicao': 'Famalicao',
        'GIL Vicente': 'Gil Vicente',
        'Guimaraes': 'Guimaraes',
        'Maritimo': 'Maritimo',
        'Moreirense': 'Moreirense',
        'Nacional': 'Nacional',
        'Rio Ave': 'Rio Ave',
        'SC Braga': 'Sp Braga',
        'Santa Clara': 'Santa Clara',
        'Sporting CP': 'Sp Lisbon',
    },
    # T1
    'T1': {
        'Adana Demirspor': 'Ad. Demirspor',
        'Alanyaspor': 'Alanyaspor',
        'Amed': 'Amed',
        'Antalyaspor': 'Antalyaspor',
        'Başakşehir': 'Buyuksehyr',
        'Beşiktaş': 'Besiktas',
        'Bodrum FK': 'Bodrumspor',
        'Erzurumspor FK': 'Erzurum BB',
        'Eyüpspor': 'Eyupspor',
        'Fenerbahçe': 'Fenerbahce',
        'Galatasaray': 'Galatasaray',
        'Gaziantep FK': 'Gaziantep',
        'Gençlerbirliği S.K.': 'Genclerbirligi',
        'Göztepe': 'Goztep',
        'Hatayspor': 'Hatayspor',
        'Kasımpaşa': 'Kasimpasa',
        'Kayserispor': 'Kayserispor',
        'Kocaelispor': 'Kocaelispor',
        'Konyaspor': 'Konyaspor',
        'Rizespor': 'Rizespor',
        'Samsunspor': 'Samsunspor',
        'Sivasspor': 'Sivasspor',
        'Trabzonspor': 'Trabzonspor',
        'Çorum FK': 'Corum',
    },
    # G1
    'G1': {
        'AEK Athens FC': 'AEK',
        'Aris Thessalonikis': 'Aris',
        'Asteras Tripolis': 'Asteras Tripolis',
        'Atromitos': 'Atromitos',
        'Iraklis 1908': 'Iraklis',
        'Kalamata': 'Kalamata',
        'Kallithea': 'Athens Kallithea',
        'Kifisia': 'Kifisia',
        'Lamia': 'Lamia',
        'Levadiakos': 'Levadeiakos',
        'OFI': 'OFI Crete',
        'Olympiakos Piraeus': 'Olympiakos',
        'PAOK': 'PAOK',
        'Panathinaikos': 'Panathinaikos',
        'Panetolikos': 'Panetolikos',
        'Panserraikos': 'Panserraikos',
        'Volos NFC': 'Volos NFC',
    },
    # ARG
    'ARG': {
        'Aldosivi': 'Aldosivi',
        'Argentinos JRS': 'Argentinos Jrs',
        'Atletico Tucuman': 'Atl. Tucuman',
        'Banfield': 'Banfield',
        'Barracas Central': 'Barracas Central',
        'Belgrano Cordoba': 'Belgrano',
        'Boca Juniors': 'Boca Juniors',
        'Central Cordoba de Santiago': 'Central Cordoba',
        'Defensa Y Justicia': 'Defensa y Justicia',
        'Deportivo Riestra': 'Dep. Riestra',
        'Estudiantes L.P.': 'Estudiantes L.P.',
        'Estudiantes de Rio Cuarto': 'Estudiantes Rio Cuarto',
        'Gimnasia L.P.': 'Gimnasia L.P.',
        'Gimnasia M.': 'Gimnasia Mendoza',
        'Huracan': 'Huracan',
        'Independ. Rivadavia': 'Ind. Rivadavia',
        'Independiente': 'Independiente',
        'Instituto Cordoba': 'Instituto',
        'Lanus': 'Lanus',
        'Newells Old Boys': 'Newells Old Boys',
        'Platense': 'Platense',
        'Racing Club': 'Racing Club',
        'River Plate': 'River Plate',
        'Rosario Central': 'Rosario Central',
        'San Lorenzo': 'San Lorenzo',
        'Sarmiento Junin': 'Sarmiento Junin',
        'Talleres Cordoba': 'Talleres Cordoba',
        'Tigre': 'Tigre',
        'Union Santa Fe': 'Union de Santa Fe',
        'Velez Sarsfield': 'Velez Sarsfield',
    },
    # AUT
    'AUT': {
        'Austria Klagenfurt': 'A. Klagenfurt',
        'Austria Lustenau': 'A. Lustenau',
        'Austria Vienna': 'Austria Vienna',
        'FC BW Linz': 'BW Linz',
        'Grazer AK': 'Grazer AK',
        'Lask Linz': 'LASK',
        'Rapid Vienna': 'SK Rapid',
        'Red Bull Salzburg': 'Salzburg',
        'Ried': 'Ried',
        'SCR Altach': 'Altach',
        'Sturm Graz': 'Sturm Graz',
        'TSV Hartberg': 'Hartberg',
        'WSG Wattens': 'Tirol',
        'Wolfsberger AC': 'Wolfsberger AC',
    },
    # BRA
    'BRA': {
        'Atletico Goianiense': 'Atletico GO',
        'Atletico Paranaense': 'Athletico-PR',
        'Atletico-MG': 'Atletico-MG',
        'Bahia': 'Bahia',
        'Botafogo': 'Botafogo RJ',
        'Chapecoense-sc': 'Chapecoense-SC',
        'Corinthians': 'Corinthians',
        'Coritiba': 'Coritiba',
        'Criciuma': 'Criciuma',
        'Cruzeiro': 'Cruzeiro',
        'Cuiaba': 'Cuiaba',
        'Flamengo': 'Flamengo RJ',
        'Fluminense': 'Fluminense',
        'Fortaleza EC': 'Fortaleza',
        'Gremio': 'Gremio',
        'Internacional': 'Internacional',
        'Juventude': 'Juventude',
        'Mirassol': 'Mirassol',
        'Palmeiras': 'Palmeiras',
        'RB Bragantino': 'Bragantino',
        'Remo': 'Remo',
        'Santos': 'Santos',
        'Sao Paulo': 'Sao Paulo',
        'Vasco DA Gama': 'Vasco',
        'Vitoria': 'Vitoria',
    },
    # CHN
    'CHN': {
        'Beijing Guoan': 'Beijing Guoan',
        'Changchun Yatai': 'Changchun Yatai',
        'Chengdu Better City': 'Chengdu Rongcheng',
        'Chongqing Tongliang Long': 'Chongqing Tonglianglong',
        'Dalian Zhixing': 'Dalian Yingbo',
        'Hangzhou Greentown': 'Hangzhou Greentown',
        'Henan Jianye': 'Henan Songshan Longmen',
        'Meizhou Kejia': 'Meizhou Hakka',
        'Nantong Zhiyun': 'Nantong Zhiyun',
        'Qingdao Jonoon': 'Qingdao FC',
        'Qingdao Youth Island': 'Qingdao West Coast',
        'SHANGHAI SIPG': 'Shanghai SIPG',
        'Shandong Luneng': 'Shandong Luneng',
        'Shanghai Shenhua': 'Shanghai Shenhua',
        'Shenyang Urban': 'Liaoning Tieren',
        'Shijiazhuang Y. J.': 'Shijiazhuang',
        'Sichuan Jiuniu': 'Shenzhen Xinpengcheng',
        'Tianjin Teda': 'Tianjin Jinmen Tiger',
        'Wuhan Three Towns': 'Wuhan Three Towns',
        'Yunnan Yukun': 'Yunnan Yukun',
    },
    # DNK
    'DNK': {
        'AC Horsens': 'Horsens',
        'Aarhus': 'Aarhus',
        'Brondby': 'Brondby',
        'FC Copenhagen': 'FC Copenhagen',
        'FC Midtjylland': 'Midtjylland',
        'FC Nordsjaelland': 'Nordsjaelland',
        'Lyngby': 'Lyngby',
        'Odense': 'Odense',
        'Randers FC': 'Randers FC',
        'Silkeborg': 'Silkeborg',
        'Sonderjyske': 'Sonderjyske',
        'Viborg': 'Viborg',
    },
    # FIN
    'FIN': {
        'AC Oulu': 'AC Oulu',
        'EIF': 'Ekenas',
        'FF Jaro': 'Jaro',
        'Gnistan': 'Gnistan',
        'HJK Helsinki': 'HJK',
        'Haka': 'Haka',
        'Ilves': 'Ilves',
        'Inter Turku': 'Inter Turku',
        'KuPS': 'KuPS',
        'Lahti': 'Lahti',
        'Mariehamn': 'Mariehamn',
        'SJK': 'SJK',
        'Turku PS': 'TPS',
        'VPS': 'VPS',
    },
    # IRL
    'IRL': {
        'Bohemians': 'Bohemians',
        'Bray Wanderers': 'Bray',
        'Derry City': 'Derry City',
        'Drogheda United': 'Drogheda',
        'Dundalk': 'Dundalk',
        'Galway United': 'Galway',
        'Shamrock Rovers': 'Shamrock Rovers',
        'Shelbourne': 'Shelbourne',
        'Sligo Rovers': 'Sligo Rovers',
        "St Patrick's Athl.": 'St. Patricks',
        'Waterford': 'Waterford',
    },
    # JPN
    'JPN': {
        'Albirex Niigata': 'Albirex Niigata',
        'Avispa Fukuoka': 'Avispa Fukuoka',
        'Cerezo Osaka': 'Cerezo Osaka',
        'Consadole Sapporo': 'Hokkaido Consadole Sapporo',
        'FC Tokyo': 'FC Tokyo',
        'Fagiano Okayama': 'Okayama',
        'Gamba Osaka': 'Gamba Osaka',
        'JEF United Chiba': 'Chiba',
        'Jubilo Iwata': 'Iwata',
        'Kashima': 'Kashima Antlers',
        'Kashiwa Reysol': 'Kashiwa Reysol',
        'Kawasaki Frontale': 'Kawasaki Frontale',
        'Kyoto Sanga': 'Kyoto',
        'Machida Zelvia': 'Machida',
        'Mito Hollyhock': 'Mito',
        'Nagoya Grampus': 'Nagoya Grampus',
        'Sagan Tosu': 'Sagan Tosu',
        'Sanfrecce Hiroshima': 'Sanfrecce Hiroshima',
        'Shimizu S-pulse': 'Shimizu S-Pulse',
        'Shonan Bellmare': 'Shonan Bellmare',
        'Tokyo Verdy': 'FC Tokyo',
        'Urawa': 'Urawa Reds',
        'V-varen Nagasaki': 'V-Varen Nagasaki',
        'Vissel Kobe': 'Vissel Kobe',
        'Yokohama F. Marinos': 'Yokohama F. Marinos',
    },
    # MEX
    'MEX': {
        'Atlante FC': 'Atlante',
        'Atlas': 'Atlas',
        'Atletico San Luis': 'Atl. San Luis',
        'CF Pachuca': 'Pachuca',
        'Club America': 'Club America',
        'Club Queretaro': 'Queretaro',
        'Club Tijuana': 'Club Tijuana',
        'Cruz Azul': 'Cruz Azul',
        'FC Juarez': 'Juarez',
        'Guadalajara Chivas': 'Guadalajara Chivas',
        'Leon': 'Club Leon',
        'Mazatlán': 'Mazatlan FC',
        'Monterrey': 'Monterrey',
        'Necaxa': 'Necaxa',
        'Puebla': 'Puebla',
        'Santos Laguna': 'Santos Laguna',
        'Tigres UANL': 'Tigres UANL',
        'Toluca': 'Toluca',
        'U.N.A.M. - Pumas': 'UNAM Pumas',
    },
    # NOR
    'NOR': {
        'Aalesund': 'Aalesund',
        'Bodo/Glimt': 'Bodo/Glimt',
        'Brann': 'Brann',
        'Fredrikstad': 'Fredrikstad',
        'Ham-Kam': 'HamKam',
        'Haugesund': 'Haugesund',
        'KFUM Oslo': 'KFUM Oslo',
        'Kristiansund BK': 'Kristiansund',
        'Lillestrom': 'Lillestrom',
        'Molde': 'Molde',
        'Moss': 'Moss',
        'ODD Ballklubb': 'Odd',
        'Rosenborg': 'Rosenborg',
        'Sandefjord': 'Sandefjord',
        'Sarpsborg 08 FF': 'Sarpsborg 08',
        'Start': 'Start',
        'Stromsgodset': 'Stromsgodset',
        'Tromso': 'Tromso',
        'Valerenga': 'Valerenga',
        'Viking': 'Viking',
    },
    # POL
    'POL': {
        'Cracovia Krakow': 'Cracovia',
        'GKS Katowice': 'GKS Katowice',
        'Gornik Zabrze': 'Gornik Zabrze',
        'Jagiellonia': 'Jagiellonia',
        'Korona Kielce': 'Korona Kielce',
        'Lech Poznan': 'Lech Poznan',
        'Lechia Gdansk': 'Lechia Gdansk',
        'Legia Warszawa': 'Legia',
        'Motor Lublin': 'Motor Lublin',
        'Piast Gliwice': 'Piast Gliwice',
        'Pogon Szczecin': 'Pogon Szczecin',
        'Puszcza Niepołomice': 'Puszcza',
        'Radomiak Radom': 'Radomiak Radom',
        'Raków Częstochowa': 'Rakow',
        'Slask Wroclaw': 'Slask Wroclaw',
        'Stal Mielec': 'Stal Mielec',
        'Widzew Łódź': 'Widzew Lodz',
        'Wieczysta Kraków': 'Wieczysta Krakow',
        'Wisla Krakow': 'Wisla',
        'Wisla Plock': 'Wisla Plock',
        'Zaglebie Lubin': 'Zaglebie',
    },
    # ROU
    'ROU': {
        'Arges Pitesti': 'FC Arges',
        'CFR 1907 Cluj': 'CFR Cluj',
        'Corvinul Hunedoara': 'Corvinul',
        'Csikszereda': 'Csikszereda M. Ciuc',
        'Dinamo Bucuresti': 'Dinamo Bucuresti',
        'FC Botosani': 'FC Botosani',
        'FC Voluntari': 'FC Voluntari',
        'FCSB': 'FCSB',
        'Farul Constanta': 'Farul Constanta',
        'Oţelul': 'Otelul',
        'Petrolul Ploiesti': 'Petrolul',
        'Rapid': 'FC Rapid Bucuresti',
        'Sepsi OSK Sfantu Gheorghe': 'Sepsi Sf. Gheorghe',
        'Universitatea Cluj': 'U. Cluj',
        'Universitatea Craiova': 'Univ. Craiova',
        'Uta Arad': 'UTA Arad',
    },
    # RUS
    'RUS': {
        'Akhmat': 'Akhmat Grozny',
        'Akron': 'Akron Togliatti',
        'Baltika': 'Baltika',
        'CSKA Moscow': 'CSKA Moscow',
        'Dinamo Makhachkala': 'Dynamo Makhachkala',
        'Dynamo': 'Dynamo Moscow',
        'FC Krasnodar': 'Krasnodar',
        'FC Orenburg': 'Orenburg',
        'FC Rostov': 'FK Rostov',
        'Fakel': 'Fakel Voronezh',
        'Krylia Sovetov': 'Krylya Sovetov',
        'Lokomotiv': 'Lokomotiv Moscow',
        'Rodina Moskva': 'Rodina Moscow',
        'Rubin': 'Rubin Kazan',
        'Spartak Moscow': 'Spartak Moscow',
        'Zenit': 'Zenit',
    },
    # SWE
    'SWE': {
        'AIK Stockholm': 'AIK',
        'BK Hacken': 'Hacken',
        'Degerfors IF': 'Degerfors',
        'Djurgardens IF': 'Djurgarden',
        'Gais': 'GAIS',
        'Halmstad': 'Halmstad',
        'Hammarby FF': 'Hammarby',
        'IF Brommapojkarna': 'Brommapojkarna',
        'IF Elfsborg': 'Elfsborg',
        'IFK Goteborg': 'Goteborg',
        'Kalmar FF': 'Kalmar',
        'Malmo FF': 'Malmo FF',
        'Mjallby AIF': 'Mjallby',
        'Orgryte IS': 'Orgryte',
        'Sirius': 'Sirius',
        'Vasteras SK FK': 'Vasteras SK',
    },
    # SWZ
    'SWZ': {
        'BSC Young Boys': 'Young Boys',
        'FC Aarau': 'Aarau',
        'FC Basel 1893': 'Basel',
        'FC Lugano': 'Lugano',
        'FC Luzern': 'Luzern',
        'FC ST. Gallen': 'St. Gallen',
        'FC Sion': 'Sion',
        'FC Thun': 'Thun',
        'FC Vaduz': 'Vaduz',
        'FC Winterthur': 'Winterthur',
        'FC Zurich': 'Zurich',
        'Grasshoppers': 'Grasshoppers',
        'Lausanne': 'Lausanne',
        'Servette FC': 'Servette',
        'Yverdon Sport': 'Yverdon',
    },
    # USA
    'USA': {
        'Atlanta United FC': 'Atlanta Utd',
        'Austin': 'Austin FC',
        'CF Montreal': 'CF Montreal',
        'Charlotte': 'Charlotte',
        'Chicago Fire': 'Chicago Fire',
        'Colorado Rapids': 'Colorado Rapids',
        'Columbus Crew': 'Columbus Crew',
        'DC United': 'DC United',
        'FC Cincinnati': 'FC Cincinnati',
        'FC Dallas': 'FC Dallas',
        'Houston Dynamo': 'Houston Dynamo',
        'Inter Miami': 'Inter Miami',
        'Los Angeles FC': 'Los Angeles FC',
        'Los Angeles Galaxy': 'Los Angeles Galaxy',
        'Minnesota United FC': 'Minnesota United',
        'Nashville SC': 'Nashville SC',
        'New England Revolution': 'New England Revolution',
        'New York City FC': 'New York City',
        'New York Red Bulls': 'New York Red Bulls',
        'Orlando City SC': 'Orlando City',
        'Philadelphia Union': 'Philadelphia Union',
        'Portland Timbers': 'Portland Timbers',
        'Real Salt Lake': 'Real Salt Lake',
        'San Diego': 'San Diego FC',
        'San Jose Earthquakes': 'San Jose Earthquakes',
        'Seattle Sounders': 'Seattle Sounders',
        'Sporting Kansas City': 'Sporting Kansas City',
        'St. Louis City': 'St. Louis City',
        'Toronto FC': 'Toronto FC',
        'Vancouver Whitecaps': 'Vancouver Whitecaps',
    },
}
